### ISSUE TITLE
Unable to compile on linux, `unresolved import winit::platform::unix`

### ISSUE THREAD

**Issue by sudormrfbin** [concoct-rs/concoct#1]
Building from `5b318b5` on Arch Linux throws the following error:

```
error[E0432]: unresolved import `winit::platform::unix`
  --> /home/gokul/.cargo/git/checkouts/glutin-0d8b72ee6b452e22/d645179/glutin-winit/src/lib.rs:29:5
   |
29 | use winit::platform::unix;
   |     ^^^^^^^^^^^^^^^^^^^^^ no `unix` in `platform`
   |
help: consider importing this module instead
   |
29 | use std::os::unix;
   |     ~~~~~~~~~~~~~~

error[E0432]: unresolved import `winit::platform::unix`
  --> /home/gokul/.cargo/git/checkouts/glutin-0d8b72ee6b452e22/d645179/glutin-winit/src/lib.rs:31:22
   |
31 | use winit::platform::unix::WindowBuilderExtUnix;
   |                      ^^^^ could not find `unix` in `platform`
```

#### Rust version

```console
$ rustc --version
rustc 1.66.1 (90743e729 2023-01-10)
```

**Comment by matthunz** [comment]
Huh I'll look into this... I've been having issues with skia compiling but this looks like `winit-glutin`.
Were you running this crate with the `all-linux` feature?

**Comment by sudormrfbin** [comment]
Nope, only the default features were used. FWIW, the `winit-glutin` dependency seems to be sourced from your personal fork at https://github.com/matthunz/glutin/tree/master/glutin-winit so the issue could stem from there?

**Comment by matthunz** [comment]
Yup exactly I just tried cross compiling from my Mac and it gave me the same error.
That fork was just for android support, but I'm gonna take that out for now until access kit supports it.
I just downgraded everything to crates.io versions, and added CI that passes on linux, so it should work now

**Comment by sudormrfbin** [comment]
It's building alright now! Closing the issue.
