### ISSUE TITLE
Use version instead from local path from examples

### ISSUE THREAD

**Issue by JADSN1894** [concoct-rs/concoct#10]
Some modules maybe is not exported correctly, when using the _version from crates.io_ instead from _local path_ from examples. Below is only the _counter_ example.

![Bug error](https://github.com/concoct-rs/concoct/assets/120682244/894d2212-c4ac-4e45-943b-f7e4a7267cc5)

**Comment by matthunz** [comment]
This looks like a bug with building but `cargo clean` fixed it for me. Let me know if that works for you too as I'd rather not pin the version just yet. The API is still very much in flux and I'd rather keep using the local dir for now if possible

**Comment by matthunz** [comment]
This should now be fixed by https://github.com/concoct-rs/concoct/commit/30165185b94a1e175386d64958b263baa9db531c as the examples are now a member of the crate workspace, so builds have been working much better.

**Comment by JADSN1894** [comment]
> This looks like a bug with building but `cargo clean` fixed it for me. Let me know if that works for you too as I'd rather not pin the version just yet. The API is still very much in flux and I'd rather keep using the local dir for now if possible

It'works.

Excellent project.

**Comment by matthunz** [comment]
Thanks! (:
